### ISSUE TITLE
Replace NA in genlight file for xvalDapc

### ISSUE THREAD

**Issue by lschiebelhut** [thibautjombart/adegenet#168]
Hello,

I am trying to replace "NA" in my genlight file to run xvalDapc.

Is there an equivalent of the following command for genlight?
X <- tab(obj, NA.method="mean")

I get the following error when I try it with my file:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘tab’ for signature ‘"genlight"’

I originally tried to use na.replace as is written in section 4.3 of the DAPC tutorial (dated 2 Sep 2016), but discovered it is not included in adegenet 2.0.2.

Thank you for your time.

Lauren

**Comment by thibautjombart** [comment]
Hi Lauren, 
thanks for the post, and sorry for the late reply. I have implemented a `tab` operator which works for `genlight` the same way as for `genind`, except that the option `NA.method = "zero"` , which doesn't make sense here, is not available. You can still use `freq` and `NA.method = "mean"`.

**Comment by bmillerlab** [comment]
Hello, I realize this person (ptcooper) asked about this a long time ago but I still have the problem with this returning a numeric matrix, not a genlight object I can continue to use for analyses like pca.
Any suggestions?
Thanks.
